#!/bin/expect

set timeout -1
set SERVER_HOSTNAME [lindex $argv 0 ];
set SERVER_IP [lindex $argv 1 ]

spawn /var/ossec/bin/manage_agents

expect "Choose your action: A,E,L,R or Q:"
sleep 2
send -- "A\r"

expect "A name for the new agent"
sleep 2
send -- "$SERVER_HOSTNAME\r"

expect "The IP Address of the new agent:"
sleep 2
send -- "$SERVER_IP\r"

expect "An ID for the new agent"
sleep 2
send -- "\r"

expect "Confirm adding it"
sleep 2
send -- "y\r"

expect "Choose your action"
sleep 2
send -- "Q\r"
